DELETE FROM BUYER;
DELETE FROM BUYS;
DELETE FROM CART;
DELETE FROM COMMERCIAL;
DELETE FROM GIFT;
DELETE FROM GIFTS;
DELETE FROM MARKET_HISTORY;
DELETE FROM PRODUCT;
DELETE FROM SELLER;
DELETE FROM SELLER_LOCATION;
DELETE FROM SELLS;
DELETE FROM TAKES;

INSERT INTO BUYER VALUES (1,'Rita','rita22@gmail.com','ri25ta',01755692567);
INSERT INTO BUYER VALUES (2,'Sumon','sumon200@gmail.com','happy2me',01759637547);
INSERT INTO BUYER VALUES (3,'Maria','maria55@gmail.com','treeLove2',01725692423);
INSERT INTO BUYER VALUES (4,'marzia','marzia25@gmail.com','mar2@',01955652558);
INSERT INTO BUYER VALUES (5,'Nahin','nahin2002@gmail.com','Nahin54',01557892437);

INSERT INTO SELLER VALUES (1,'Ritu','ritu2200@gmail.com','ri252ta',01755692567 ,1);
INSERT INTO SELLER VALUES (2,'Sumona','sumona2005@gmail.com','treeMe',01747538235 ,2);

INSERT INTO PRODUCT VALUES (1, 'Rose',2 ,'Tree');
INSERT INTO PRODUCT VALUES (2, 'Sunflower',5 ,'Seed');
INSERT INTO PRODUCT VALUES (3, 'Sunflower',7 ,'Seed');
INSERT INTO PRODUCT VALUES (4, 'Marigold',5 ,'Tree');

INSERT INTO GIFT VALUES (1);
INSERT INTO GIFT VALUES (3);

INSERT INTO COMMERCIAL VALUES (2 , 100);
INSERT INTO COMMERCIAL VALUES (4 , 300);


INSERT INTO SELLS VALUES (1 , 4);

INSERT INTO BUYS VALUES (2 , 4);


INSERT INTO GIFTS VALUES (2 , 3);

INSERT INTO TAKES VALUES (3 , 3);


INSERT INTO SELLER_LOCATION VALUES (1 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 5');
INSERT INTO SELLER_LOCATION VALUES (2 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 3');
INSERT INTO SELLER_LOCATION VALUES (3 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 1');
INSERT INTO SELLER_LOCATION VALUES (4 ,'Dhaka' ,'Ramna', 'Polashi', 'road no - 10');
INSERT INTO SELLER_LOCATION VALUES (5 ,'Dinajpur' ,'Dinajpur Sadar', 'Motinogor', 'road no - 21');
INSERT INTO SELLER_LOCATION VALUES (6 ,'Pabna' ,'Pabna Sadar', 'Kalitola', 'road no - 13');
INSERT INTO SELLER_LOCATION VALUES (7 ,'Khulna' ,'Khulna Sadar', 'Mastarpara', 'road no - 11');
INSERT INTO SELLER_LOCATION VALUES (8 ,'Bogura' ,'Bogra Sadar', 'Uposhohor', 'road no - 17');
INSERT INTO SELLER_LOCATION VALUES (9 ,'Rajshahi' ,'Bagha', 'Courtpara', 'road no - 31');
INSERT INTO SELLER_LOCATION VALUES (10 ,'Dhaka' ,'Savar', 'Gopibag', 'road no - 18');


INSERT INTO MARKET_HISTORY VALUES (1 , 2 ,1 ,4 , 2 ,SYSDATE);
INSERT INTO MARKET_HISTORY VALUES (2 , 3 ,2 ,3 , 1, SYSDATE);

INSERT INTO PRODUCT_IN_CART VALUES (2 , 1, 2, 50);

