DELETE FROM BUYER;
DELETE FROM COMMERCIAL;
DELETE FROM COMMERCIAL_OWNER;
DELETE FROM COMMERCIAL_RECEIVER;
DELETE FROM GIFT;
DELETE FROM GIFT_OWNER;
DELETE FROM GIFT_RECEIVER;
DELETE FROM MARKET_HISTORY;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_IN_CART;
DELETE FROM SELLER;
DELETE FROM SELLER_LOCATION;


INSERT INTO SELLER_LOCATION VALUES (1 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 5');
INSERT INTO SELLER_LOCATION VALUES (2 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 3');
INSERT INTO SELLER_LOCATION VALUES (3 ,'Rajshahi' ,'Bogra Sadar', 'Maltinogor', 'road no - 1');
INSERT INTO SELLER_LOCATION VALUES (4 ,'Dhaka' ,'Ramna', 'Polashi', 'road no - 10');
INSERT INTO SELLER_LOCATION VALUES (5 ,'Dinajpur' ,'Dinajpur Sadar', 'Motinogor', 'road no - 21');
INSERT INTO SELLER_LOCATION VALUES (6 ,'Pabna' ,'Pabna Sadar', 'Kalitola', 'road no - 13');
INSERT INTO SELLER_LOCATION VALUES (7 ,'Khulna' ,'Khulna Sadar', 'Mastarpara', 'road no - 11');
INSERT INTO SELLER_LOCATION VALUES (8 ,'Bogura' ,'Bogra Sadar', 'Uposhohor', 'road no - 17');
INSERT INTO SELLER_LOCATION VALUES (9 ,'Rajshahi' ,'Bagha', 'Courtpara', 'road no - 31');
INSERT INTO SELLER_LOCATION VALUES (10 ,'Dhaka' ,'Savar', 'Gopibag', 'road no - 18');

INSERT INTO BUYER VALUES (1,'Rita','rita22@gmail.com','ri25ta',01755692567);
INSERT INTO BUYER VALUES (2,'Adiba','sumon200@gmail.com','happy2me',01759637547);
INSERT INTO BUYER VALUES (3,'Maria','maria55@gmail.com','treeLove2',01725692423);
INSERT INTO BUYER VALUES (4,'Nuha','marzia25@gmail.com','mar2@',01955652558);
INSERT INTO BUYER VALUES (5,'Nahin','nahin2002@gmail.com','Nahin54',01557892437);

INSERT INTO SELLER VALUES (1,'Ritu','ritu2200@gmail.com','ri252ta',01755692567 ,1);
INSERT INTO SELLER VALUES (2,'Oishi','oishi2005@gmail.com','treeMe11',01747538235 ,2);
INSERT INTO SELLER VALUES (3,'Arpita','arpita2005@gmail.com','tred22',01747538235 ,6);
INSERT INTO SELLER VALUES (4,'Swastika','swastika2005@gmail.com','swas993',01747538235 ,9);
INSERT INTO SELLER VALUES (5,'Saba','saba2005@gmail.com','sabatre22e',01747538235 ,10);

INSERT INTO PRODUCT VALUES (1, 'Rose',10 ,'Plant');
INSERT INTO PRODUCT VALUES (2, 'Sunflower',10 ,'Plant');
INSERT INTO PRODUCT VALUES (3, 'Sunflower',20 ,'Seed');
INSERT INTO PRODUCT VALUES (4, 'Marigold',25 ,'Plant');
INSERT INTO PRODUCT VALUES (5, 'Orange',15 ,'Plant');

INSERT INTO GIFT VALUES (1);
INSERT INTO GIFT VALUES (3);

INSERT INTO COMMERCIAL VALUES (2 , 100);
INSERT INTO COMMERCIAL VALUES (5 , 300);
INSERT INTO COMMERCIAL VALUES (4 , 50);

INSERT INTO COMMERCIAL_OWNER VALUES (1 , 5);
INSERT INTO COMMERCIAL_OWNER VALUES (2 , 2);
INSERT INTO COMMERCIAL_OWNER VALUES (4 , 4);

INSERT INTO COMMERCIAL_RECEIVER VALUES (2 , 4);
INSERT INTO COMMERCIAL_RECEIVER VALUES (1 , 2);
INSERT INTO COMMERCIAL_RECEIVER VALUES (3 , 5);

INSERT INTO GIFT_OWNER VALUES (1 , 1);
INSERT INTO GIFT_OWNER VALUES (5 , 3);

INSERT INTO GIFT_RECEIVER VALUES (2 , 1);
INSERT INTO GIFT_RECEIVER VALUES (4 , 3);

INSERT INTO MARKET_HISTORY VALUES (1 , 1 ,3 ,5 , 2, SYSDATE);
INSERT INTO MARKET_HISTORY VALUES (2 , 2 ,1 ,2 , 2, SYSDATE);
INSERT INTO MARKET_HISTORY VALUES (3 , 4 ,2 ,4 , 2, SYSDATE);
INSERT INTO MARKET_HISTORY VALUES (4 , 1 ,2 ,1 , 2, SYSDATE);
INSERT INTO MARKET_HISTORY VALUES (5 , 5 ,4 ,3 , 2, SYSDATE);

INSERT INTO PRODUCT_IN_CART VALUES (2 , 4, 2, 50);