DECLARE
C NUMBER;
BEGIN
SELECT COUNT(*) INTO C FROM BUYER;
C:=C+1;
--DBMS_OUTPUT.PUT_LINE(C) ;

END;

-----------

DECLARE
L VARCHAR2(100);
BEGIN
SELECT LOCATION_ID INTO L FROM SELLER_LOCATION 
WHERE UPPER(DISTRICT)='RAJSHAHI' AND UPPER(THANA)='BOGURA SADAR' AND UPPER(AREA)='MALOTINOGOR' AND UPPER(DETAILS)='ROAD NO - 5';
--DBMS_OUTPUT.PUT_LINE(L) ;
END;

------------

SELECT PRODUCT_ID ,PRODUCT_NAME, AVAILABLE_QUANTITY FROM PRODUCT
WHERE LOWER(CATEGORY)='plant';


-----------


SELECT S.NAME, S.EMAIL, S.CONTACT, L.DISTRICT, L.THANA, L.AREA, L.DETAILS 
FROM SELLER S JOIN SELLER_LOCATION L ON (S.LOCATION_ID=L.LOCATION_ID) 
WHERE S.EMAIL='ritu2200@gmail.com' AND S.PASSWORD='ri252ta';


------------

SELECT P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
FROM PRODUCT P JOIN COMMERCIAL C ON (P.PRODUCT_ID=C.PRODUCT_ID)
WHERE P.CATEGORY='plant';


---------------

SELECT P.PRODUCT_NAME, P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G ON (P.PRODUCT_ID=G.PRODUCT_ID)
WHERE P.CATEGORY='plant';

-------

DELETE FROM BUYER WHERE BUYER_ID=2;

----------

DECLARE
C NUMBER;
BEGIN
SELECT MAX(BUYER_ID) INTO C FROM BUYER;
C:=C+1;
DBMS_OUTPUT.PUT_LINE(C);
END;


DECLARE
C NUMBER;
BEGIN
SELECT MAX(BUYER_ID) INTO C FROM BUYER;
C:=C+1;
INSERT INTO BUYER (BUYER_ID, NAME, EMAIL, PASSWORD, CONTACT) VALUES (C,'adiba','adiba@gmail.com','123ad','01234567896');
COMMIT;
END;

--------

select * from SELLER_LOCATION where DISTRICT='Rangpur';

--------







DROP TRIGGER NEW_LOCATION;


----------

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
        FROM PRODUCT P JOIN COMMERCIAL C ON (P.PRODUCT_ID=C.PRODUCT_ID)
        WHERE P.CATEGORY='plant';


-----------

SELECT P.PRODUCT_ID, P.PRODUCT_NAME ,P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G
ON P.PRODUCT_ID = G.PRODUCT_ID
WHERE P.CATEGORY = 'plant' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('ang'))>0 ;

--new location trigger when seller is signing up, if the location is new, then...


-- CREATE OR REPLACE TRIGGER NEW_LOCATION
-- BEFORE INSERT ON SELLER
-- FOR EACH ROW
-- DECLARE
-- CNT NUMBER;
-- LID NUMBER;
-- L NUMBER;
-- BEGIN
-- 
-- SELECT MAX(LOCATION_ID) INTO LID FROM SELLER_LOCATION;
-- 
-- SELECT COUNT(*) INTO CNT FROM SELLER_LOCATION 
-- WHERE DISTRICT=:NEW.DISTRICT AND THANA=:NEW.THANA AND AREA=:NEW.AREA AND DETAILS=:NEW.DETAILS;
-- 
-- IF CNT=0 THEN
-- LID:=LID+1;
-- INSERT INTO SELLER_LOCATION (LOCATION_ID, DISTRICT, THANA, AREA, DETAILS) VALUES (LID, :NEW.DISTRICT, :NEW.THANA, :NEW.AREA, :NEW.DETAILS);
-- 	
-- :NEW.LOCATION_ID:=LID;
-- 
-- ELSE
-- SELECT LOCATION_ID INTO L FROM SELLER_LOCATION WHERE DISTRICT=:NEW.DISTRICT AND THANA=:NEW.THANA AND AREA=:NEW.AREA AND DETAILS=:NEW.DETAILS;
-- 
-- :NEW.LOCATION_ID:=L;
-- 
-- END IF;
-- END;
-- /




-- INSERT INTO SELLER (SELLER_ID, NAME, EMAIL, PASSWORD, CONTACT, LOCATION_ID) VALUES (42, 'monisha', 'monisha@gmail.com', 'mon5', '01718998877', 1);
-- 
-- 
-- 
-- 
-- show error;
-- 
-- 
-- 
-- SELECT * FROM DBA_ERRORS WHERE NAME = 'NEW_LOCATION';
-- 
-- ALTER TRIGGER NEW_LOCATION COMPILE;

