DECLARE
C NUMBER;
BEGIN
SELECT COUNT(*) INTO C FROM BUYER;
C:=C+1;
--DBMS_OUTPUT.PUT_LINE(C) ;

END;

-----------

DECLARE
L VARCHAR2(100);
BEGIN
SELECT LOCATION_ID INTO L FROM SELLER_LOCATION 
WHERE UPPER(DISTRICT)='RAJSHAHI' AND UPPER(THANA)='BOGURA SADAR' AND UPPER(AREA)='MALOTINOGOR' AND UPPER(DETAILS)='ROAD NO - 5';
--DBMS_OUTPUT.PUT_LINE(L) ;
END;

------------

SELECT PRODUCT_ID ,PRODUCT_NAME, AVAILABLE_QUANTITY FROM PRODUCT
WHERE LOWER(CATEGORY)='plant';


-----------


SELECT S.NAME, S.EMAIL, S.CONTACT, L.DISTRICT, L.THANA, L.AREA, L.DETAILS 
FROM SELLER S JOIN SELLER_LOCATION L ON (S.LOCATION_ID=L.LOCATION_ID) 
WHERE S.EMAIL='ritu2200@gmail.com' AND S.PASSWORD='ri252ta';


------------

SELECT P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
FROM PRODUCT P JOIN COMMERCIAL C ON (P.PRODUCT_ID=C.PRODUCT_ID)
WHERE P.CATEGORY='plant';


---------------

SELECT P.PRODUCT_NAME, P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G ON (P.PRODUCT_ID=G.PRODUCT_ID)
WHERE P.CATEGORY='plant';
