SELECT * FROM PRODUCT


SELECT * FROM PRODUCT
WHERE CATEGORY = 'Seed';


SELECT * FROM PRODUCT
WHERE CATEGORY = 'Plant';


/*BUYER DELETE TRIGGER*/
CREATE TABLE BUYER_DELETED(
BUYER_NAME VARCHAR2(50),
BUYER_EMAIL VARCHAR2(50),
BUYER_CONTACT CHAR(30)
);

CREATE OR REPLACE TRIGGER BACKUP_DELETED_BUYER 
BEFORE DELETE
ON BUYER
FOR EACH ROW 
DECLARE
D_NAME VARCHAR2(50);
D_EMAIL VARCHAR2(50);
D_CONTACT CHAR(30);
BEGIN
D_NAME := :OLD.NAME;
D_EMAIL := :OLD.EMAIL;
D_CONTACT := :OLD.CONTACT;
INSERT INTO BUYER_DELETED VALUES(D_NAME, D_EMAIL, D_CONTACT);
END;

DELETE FROM BUYER WHERE BUYER_ID = 46;




/*SELLER DELETE TRIGGER*/
CREATE TABLE SELLER_DELETED(
SELLER_NAME VARCHAR2(50),
SELLER_EMAIL VARCHAR2(50),
SELLER_CONTACT CHAR(30),
SELLER_LOCATION_ID INTEGER
);

CREATE OR REPLACE TRIGGER BACKUP_DELETED_SELLER 
BEFORE DELETE
ON SELLER 
FOR EACH ROW 
DECLARE
D_NAME VARCHAR2(50);
D_EMAIL VARCHAR2(50);
D_CONTACT CHAR(30);
D_LOCATION_ID INTEGER;
BEGIN
D_NAME := :OLD.NAME;
D_EMAIL := :OLD.EMAIL;
D_CONTACT := :OLD.CONTACT;
D_LOCATION_ID := :OLD.LOCATION_ID;
INSERT INTO SELLER_DELETED VALUES(D_NAME, D_EMAIL, D_CONTACT, D_LOCATION_ID);
END;


DELETE FROM SELLER WHERE SELLER_ID = 46;


DROP TRIGGER BACKUP_DELETED_SELLER;


/*gift queries*/
-- SELECT P.PRODUCT_ID, P.PRODUCT_NAME ,P.AVAILABLE_QUANTITY
-- FROM PRODUCT P JOIN GIFT G
-- ON P.PRODUCT_ID = G.PRODUCT_ID
-- WHERE P.CATEGORY = 'plant' AND P.PRODUCT_NAME LIKE '%ang%' ;

SELECT P.PRODUCT_ID, P.PRODUCT_NAME ,P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G
ON P.PRODUCT_ID = G.PRODUCT_ID
WHERE P.CATEGORY = 'plant' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('ang'))>0 ;


SELECT P.PRODUCT_ID, P.PRODUCT_NAME ,P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G
ON P.PRODUCT_ID = G.PRODUCT_ID
WHERE P.CATEGORY = 'seed' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('as'))>0 ;


SELECT P.PRODUCT_ID, P.PRODUCT_NAME ,P.AVAILABLE_QUANTITY
FROM PRODUCT P JOIN GIFT G
ON P.PRODUCT_ID = G.PRODUCT_ID
WHERE P.CATEGORY = 'accessories' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('hear'))>0 ;



/*commercial queries*/
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
FROM PRODUCT P JOIN COMMERCIAL C
ON P.PRODUCT_ID = C.PRODUCT_ID
WHERE P.CATEGORY ='plant' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('flower'))>0 ;


SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
FROM PRODUCT P JOIN COMMERCIAL C
ON P.PRODUCT_ID = C.PRODUCT_ID
WHERE P.CATEGORY ='seed' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('flower'))>0 ;


SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.AVAILABLE_QUANTITY, C.PRICE
FROM PRODUCT P JOIN COMMERCIAL C
ON P.PRODUCT_ID = C.PRODUCT_ID
WHERE P.CATEGORY ='accessories' AND INSTR(UPPER(P.PRODUCT_NAME),UPPER('ose'))>0 ;


