CREATE TABLE SELLER(
SELLER_ID INTEGER,
NAME VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50),
PASSWORD VARCHAR2(30) NOT NULL,
CONTACT INTEGER NOT NULL,
LOCATION_ID INTEGER NOT NULL,
PRIMARY KEY(SELLER_ID)
);

CREATE TABLE BUYER(
BUYER_ID INTEGER,
NAME VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50),
PASSWORD VARCHAR2(30) NOT NULL,
CONTACT INTEGER NOT NULL,
PRIMARY KEY(BUYER_ID)
);


CREATE TABLE SELLER_LOCATION(
LOCATION_ID INTEGER,
DISTRICT VARCHAR2(50) NOT NULL,
THANA VARCHAR2(50) NOT NULL,
AREA VARCHAR2(50) NOT NULL,
DETAILS VARCHAR2(80),
PRIMARY KEY(LOCATION_ID)
);


CREATE TABLE PRODUCT(
PRODUCT_ID INTEGER,
PRODUCT_NAME VARCHAR2(80) NOT NULL,
AVAILABLE_QUANTITY INTEGER NOT NULL,
CATEGORY VARCHAR2(30) NOT NULL,
PRIMARY KEY(PRODUCT_ID)
);


CREATE TABLE GIFT(
PRODUCT_ID INTEGER PRIMARY KEY,
FOREIGN KEY(PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)
ON DELETE CASCADE
);


CREATE TABLE COMMERCIAL(
PRODUCT_ID INTEGER PRIMARY KEY,
PRICE FLOAT NOT NULL,
FOREIGN KEY(PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)
ON DELETE CASCADE
);


CREATE TABLE GIFTS(
SELLER_ID INTEGER,
PRODUCT_ID INTEGER,
PRIMARY KEY(SELLER_ID, PRODUCT_ID),
FOREIGN KEY(SELLER_ID)
REFERENCES SELLER(SELLER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRODUCT_ID)
REFERENCES GIFT(PRODUCT_ID)
ON DELETE CASCADE
);



CREATE TABLE SELLS(
SELLER_ID INTEGER,
PRODUCT_ID INTEGER,
PRIMARY KEY(SELLER_ID, PRODUCT_ID),
FOREIGN KEY(SELLER_ID)
REFERENCES SELLER(SELLER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRODUCT_ID)
REFERENCES COMMERCIAL(PRODUCT_ID)
ON DELETE CASCADE
);


CREATE TABLE TAKES(
BUYER_ID INTEGER,
PRODUCT_ID INTEGER,
PRIMARY KEY(BUYER_ID, PRODUCT_ID),
FOREIGN KEY(BUYER_ID)
REFERENCES BUYER(BUYER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRODUCT_ID)
REFERENCES GIFT(PRODUCT_ID)
ON DELETE CASCADE
);


CREATE TABLE BUYS(
BUYER_ID INTEGER,
PRODUCT_ID INTEGER,
PRIMARY KEY(BUYER_ID, PRODUCT_ID),
FOREIGN KEY(BUYER_ID)
REFERENCES BUYER(BUYER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRODUCT_ID)
REFERENCES COMMERCIAL(PRODUCT_ID)
ON DELETE CASCADE
);


CREATE TABLE MARKET_HISTORY(
HISTORY_ID INTEGER PRIMARY KEY,
BUYER_ID INTEGER,
SELLER_ID INTEGER,
PRODUCT_ID INTEGER,
QUANTITY INTEGER NOT NULL,
HISTORY_DATE DATE NOT NULL,
FOREIGN KEY(SELLER_ID)
REFERENCES SELLER(SELLER_ID)
ON DELETE SET NULL,
FOREIGN KEY(BUYER_ID)
REFERENCES BUYER(BUYER_ID)
ON DELETE SET NULL,
FOREIGN KEY(PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)
ON DELETE SET NULL
);


CREATE TABLE PRODUCT_IN_CART(
BUYER_ID INTEGER,
PRODUCT_ID INTEGER,
QUANTITY INTEGER NOT NULL,
PRICE_PER_PIECE FLOAT NOT NULL,
FOREIGN KEY(BUYER_ID)
REFERENCES BUYER(BUYER_ID)
ON DELETE CASCADE,
FOREIGN KEY(PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)
ON DELETE CASCADE
);




